# permissions for end users to view movies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: movies-viewer-role
rules:
- apiGroups:
  - rating.tanisha.banik
  resources:
  - movies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rating.tanisha.banik
  resources:
  - movies/status
  verbs:
  - get
